FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY HaliteBot/*.csproj ./HaliteBot/
RUN dotnet restore

# copy everything else and build app
COPY HaliteBot/. ./HaliteBot/
COPY HaliteBot/hlt/. ./HaliteBot/hlt/
WORKDIR /app/HaliteBot
RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS runtime
WORKDIR /app
COPY --from=build /app/HaliteBot/out ./
ENTRYPOINT ["dotnet", "HaliteBot.dll"]